name: Build & Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    # Use the "docker" environment where you've configured env vars & secrets
    environment: docker  
    runs-on: ubuntu-latest

    steps:
      # 1) Check out code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Build the Docker image
      #    This calls your script inside "build/" folder.
      #    Make sure build.sh runs "docker build -t $DOCKERHUB_REPO:$IMAGE_TAG ."
      - name: Build Docker Image
        run: |
          cd build
          chmod +x build.sh
          ./build.sh

      # 3) Login to Docker Hub using the DOCKERHUB_TOKEN secret
      - name: Docker Hub Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
            -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      # 4) Push the Docker image (using environment variables DOCKERHUB_REPO & IMAGE_TAG)
      - name: Push Docker Image
        run: |
          docker push "${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}"

      # 5) Create a GitHub Release referencing the Docker image tag
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.IMAGE_TAG }}
          release_name: "Release ${{ env.IMAGE_TAG }}"
          body: "Docker image: ${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}"
          draft: false
          prerelease: false
        env:
          # Provided automatically by GitHub to allow release creation
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
