name: Build & Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    environment: docker  # Ties to your environment "docker"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build Docker Images
        run: |
          cd build
          chmod +x build.sh
          ./build.sh

      - name: Debug secrets (optional)
        run: |
          echo "DOCKERHUB_REPO length: ${#${{ secrets.DOCKERHUB_REPO }}}"
          echo "DOCKERHUB_IMAGE_TAG length: ${#${{ secrets.DOCKERHUB_IMAGE_TAG }}}"

      - name: Tag final image
        run: |
          docker tag local/openvpn-ui:latest "${{ secrets.DOCKERHUB_REPO }}:${{ secrets.DOCKERHUB_IMAGE_TAG }}"

      - name: Push Docker Image
        run: |
          docker push "${{ secrets.DOCKERHUB_REPO }}:${{ secrets.DOCKERHUB_IMAGE_TAG }}"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ secrets.DOCKERHUB_IMAGE_TAG }}
          release_name: "Release ${{ secrets.DOCKERHUB_IMAGE_TAG }}"
          body: "Docker image: ${{ secrets.DOCKERHUB_REPO }}:${{ secrets.DOCKERHUB_IMAGE_TAG }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
